# Generated by Django 3.0.8 on 2020-07-14 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymusic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='albumtitle',
            new_name='album_Title',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='artistname',
            new_name='artist_Name',
        ),
    ]
