# Generated by Django 3.0.8 on 2020-07-14 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymusic', '0003_auto_20200714_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_Title',
            new_name='album_title',
        ),
    ]
